default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: uv-lock-update
        name: Update uv-lock
        entry: scripts/update_uv_lock.sh lock
        language: system
        files: ^(.*/)?(pyproject\.toml|uv-lock)$
        pass_filenames: false
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "--verbose",
            "--scope",
            "data,src,lib,munge,docs,config",
            "feat",
            "fix",
            "docs",
            "refactor",
            "style",
            "test",
            "chore",
            "ci",
            "perf",
            "revert",
            "build",
            "security",
            "types",
            "deps",
            "release",
          ]